language: java

jdk:
- openjdk8
- openjdk11

# Overridden because parent project uses maven.test.skip instead of skipTests
install:
  - mvn package -q -Dmaven.test.skip -Dmaven.javadoc.skip -B -V

script:
  - mvn -q help:active-profiles verify

after_success:
  - chmod 755 src/main/tools/travis/*
  - src/main/tools/travis/get_build_key $encrypted_caea2c9f1550_key $encrypted_caea2c9f1550_iv
  - src/main/tools/travis/deploy

cache:
  directories:
  - $HOME/.m2

# The only branch we build on is master; all other builds are done on PRs to master
branches:
  only:
  - main

notifications:
  email:
    recipients:
    - ksclarke@ksclarke.io
    on_failure: change
    on_success: change

sudo: false
